<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EvilBaschdi.Core" Version="2026.6.18.15" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="EvilBaschdi.About.Avalonia" Version="2026.7.29.16" />
    <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2026.8.3.15" />
    <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2026.3.12.17" />
    <PackageVersion Include="EvilBaschdi.Core.Settings" Version="2026.3.12.17" />
  </ItemGroup>
</Project>