<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EvilBaschdi.Core" Version="2026.6.18.15" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.5" />
    <PackageVersion Include="WpfAnalyzers" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="EvilBaschdi.About.Avalonia" Version="2026.7.26.9" />
    <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2026.7.26.9" />
    <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2026.3.12.17" />
    <PackageVersion Include="EvilBaschdi.Core.Settings" Version="2026.3.12.17" />
  </ItemGroup>
</Project>